// Generated by CoffeeScript 1.7.1
var Site, config, mySite;

Site = require('./mySite').Site;

config = {
  source: 'test/site',
  livereload: 35729,
  server_config: {
    port: 1337
  }
};

console.log("Building " + config.source + "...");

console.time('Site Built in');

mySite = new Site(config, function(err) {
  if (err != null) {
    return console.error(err);
  }
  console.timeEnd('Site Built in');
  console.log("Starting Server...");
  console.time('Server Started in');
  return mySite.serve(function(address) {
    console.timeEnd('Server Started in');
    return console.log("Started at http://" + address.address + ":" + address.port);
  });
});

//# sourceMappingURL=test.map
