// Generated by CoffeeScript 1.7.1
var Proxy, configFile, httpProxy,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

configFile = require('./config-file');

httpProxy = require('http-proxy');

module.exports.Proxy = Proxy = (function(_super) {
  __extends(Proxy, _super);

  function Proxy() {
    Proxy.__super__.constructor.apply(this, arguments);
  }

  Proxy.prototype.handler = function() {
    var proxy;
    proxy = new httpProxy.createProxyServer({
      target: this.data.target
    });
    return (function(_this) {
      return function(req, res, next) {
        return proxy.web(req, res);
      };
    })(this);
  };

  return Proxy;

})(configFile.ConfigFile);

//# sourceMappingURL=proxy.map
